// Do not modify. Generated by ./rebuild.sh
var GENERATED = {}
GENERATED.themes = [
"codesearch-theme monokai",
"codesearch-theme spacecadet",
"codesearch-theme twilight",
"codesearch-theme blackboard",
"codesearch-theme espresso-libre",
"codesearch-theme pastels-on-dark",
"codesearch-theme zenburnesque",
"" // original native theme
];
