// Do not modify. Generated by ./build.sh
var GENERATED = {}
GENERATED.themes = [
"_CST_ zenburnesque",
"_CST_ twilight",
"_CST_ spacecadet",
"_CST_ pastels-on-dark",
"_CST_ monokai",
"_CST_ espresso-libre",
"_CST_ cobalt",
"_CST_ blackboard",
"" // original native theme
];
