#!/bin/bash

function clean() {
  rm less/gen/*.less
  rm css/gen/*.css
  rm -r less/gen
  rm -r css/gen
}

function themes() {
  for t in $(cat theme.list.txt); do
    if [ -f "less/themes/$t.less" ]; then
      echo $t
    else
      echo "Note: '$t' is non-existing" 1>&2
    fi
  done
}

function check_themes() {
  loc=$(cd less/themes && ls -tr *.less | sed 's/.less//')
  lis=$(themes)
  tmp1=$(mktemp)
  tmp2=$(mktemp)
  echo $loc | xargs -n 1 | sort > $tmp1
  echo $lis | xargs -n 1 | sort > $tmp2
  tmp=$(mktemp)
  diff --unchanged-group-format= --changed-group-format=%\> \
    --new-line-format='%l' -biw $tmp2 $tmp1 >> $tmp
  if [ $? -ne 0 ]; then
    cat $tmp | xargs -n1 >> theme.list.txt
    echo "Updated themes file" 1>&2
  fi
  rm $tmp $tmp1 $tmp2
}

check_themes

jstmp=$(mktemp)
echo '// Do not modify. Generated by '$0 > $jstmp
echo 'var GENERATED = {}' >> $jstmp
echo 'GENERATED.themes = [' >> $jstmp

mkdir -p css/gen 2>/dev/null
mkdir -p less/gen 2>/dev/null

for file in $(themes 2>/dev/null); do

  lesstmp="less/gen/$file.less"
  echo '// Do not modify. Generated by '$0 > $lesstmp
  echo "._CST_.$file {" >> $lesstmp
  echo "  @import \"../base/styles.less\";" >> $lesstmp
  echo "  @import \"../themes/$file.less\";" >> $lesstmp
  echo "}" >> $lesstmp

  csstmp="css/gen/$file.css"
  lessc $lesstmp $csstmp --verbose --clean-css 1>&2 || exit $?


  echo '"_CST_ '$file'",' >> $jstmp

done;
echo '"" // original native theme' >> $jstmp
echo '];' >> $jstmp
cat css/gen/*.css > css/generated.css
mv $jstmp js/generated.js

clean

exit 0
