#!/bin/bash

function clean(){
  rm less/generated.less
  rm less/gen/*.less
  rm css/gen/*.css
  rm -r less/gen
  rm -r css/gen
}

jstmp=$(mktemp)
echo '// Do not modify. Generated by '$0 > $jstmp
echo 'var GENERATED = {}' >> $jstmp
echo 'GENERATED.themes = [' >> $jstmp

mkdir -p css/gen 2>/dev/null
mkdir -p less/gen 2>/dev/null

for file in $(cd less/themes && ls -tr *.less | sed 's/.less//'); do

  lesstmp="less/gen/$file.less"
  echo '// Do not modify. Generated by '$0 > $lesstmp
  echo "._CST_.$file {" >> $lesstmp
  echo "  @import \"../base/styles.less\";" >> $lesstmp
  echo "  @import \"../themes/$file.less\";" >> $lesstmp
  echo "}" >> $lesstmp

  csstmp="css/gen/$file.css"
  lessc $lesstmp $csstmp --verbose --clean-css  || exit $?


  echo '"_CST_ '$file'",' >> $jstmp

done;
echo '"" // original native theme' >> $jstmp
echo '];' >> $jstmp
mv $lesstmp less/generated.less
cat css/gen/*.css > css/generated.css
mv $jstmp js/generated.js

clean

exit 0
